### PR TITLE
Adding 'private' to package.json to avoid accidental npm publish

### PR DESCRIPTION
**Pull request by MSLaguana**

### CODE REVIEW

**Comment by digeff** [comment]
:+1: as long as we know for sure this won't mess anything in the marketplace

**Comment by MSLaguana** [comment]
It hasn't caused any issues for the react-native extension, so it should be fine. The only meaning that I'm aware of is to not allow you to `npm publish` a package.

**Comment by digeff** [comment]
Great! Go for it!

**Comment by meenakb** [comment]
:package: :+1:

**Pull request merged**
