### PR TITLE
fix error extending Window

### PR DESCRIPTION
**Pull request by ridomin**
This will fix the error: TS2430: Build:Interface 'InAppBrowser' incorrectly extends interface 'Window'

### CODE REVIEW

**Comment by MSLaguana** [comment]
Looks like this is a similar fix to https://github.com/DefinitelyTyped/DefinitelyTyped/commit/20762bfa1c3bbb08d17e66b2826ac73ed3085f82

I'd suggest also making the changes to the comment as they do there, or more specifically taking the latest version from definitelytyped which also has a couple of other minor changes.

**Comment by ridomin** [comment]
Including changes in comments, however I there is still a delta, since the DT version does not include this https://github.com/Microsoft/vscode-cordova/commit/4b3fa677d3c9505388e686a7f3ea22ce372cb50f

**Comment by MSLaguana** [comment]
Looks good to me. Thanks Rido

**Comment by dlebu** [comment]
Thank you @ridomin!

**Pull request merged**
