### PR TITLE
Fix missing platform error message for Ionic

### PR DESCRIPTION
**Pull request by janpio**
Ionic CLI command is `ionic cordova platform add ...`

### CODE REVIEW

**Comment by iTOYS** [comment]
Hi @janpio,
Thanks for contributing! But it is is not work with Ionic@2

**Comment by janpio** [comment]
If you refer to Ionic CLI, yes, this does not work with Ionic CLI 2.x. But the current version has been 3.x now for quite some time. The current output does not work with Ionic CLI 3.x.

(Does the rest of this extension use `ionic cordova` commands for everything?)

**Comment by iTOYS** [comment]
Extension use `ionic cordova` command for Ionic CLI@3 or greater otherwise just `ionic` command.
https://github.com/Microsoft/vscode-cordova/blob/master/src/debugger/extension.ts#L110L112

**Comment by janpio** [comment]
Ahh. Ok, so the same should be done to this error message then, correct?

**Comment by iTOYS** [comment]
Yes, something like that.

**Comment by svekl** [comment]
@iTOYS Please, close this PR, fixed this message in #366

**Pull request closed without merging**
