### PR TITLE
Prepare for 1.8.0

### PR DESCRIPTION
**Pull request by ruslan-bikkinin**

### CODE REVIEW

**Comment by LiamKarlMitchell** [comment]
Will 1.8.0 include the fix for renamed commands?

```The run command has been renamed. To find out more, run:

     ionic cordova run --help```

**Comment by ruslan-bikkinin** [comment]
@LiamKarlMitchell thanks for pointing to that! Yeah, we'll include fix for it, as well. Is it for `Ionic: Run`  palette command only, I assume?

**Comment by CodeDoctor34** [comment]
Any idea when the next release will be available?

**Comment by ruslan-bikkinin** [comment]
@CodeDoctor34 1.8.0 is just been released.

**Pull request merged**
